[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "RL"
authors = [{name = "Bo", email = "bborg.yin@gmail.com"}]
dynamic = ["version", "description"]
